/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.quarkus.component.mina.sftp.it;

import java.net.URI;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import org.apache.camel.CamelContext;
import org.apache.camel.ConsumerTemplate;
import org.apache.camel.Exchange;
import org.apache.camel.ProducerTemplate;
import org.jboss.logging.Logger;

@Path("/mina-sftp")
@ApplicationScoped
public class MinaSftpResource {

    private static final Logger LOG = Logger.getLogger(MinaSftpResource.class);

    private static final String COMPONENT_MINA_SFTP = "mina-sftp";
    private static final long TIMEOUT_MS = 5000; // Increased timeout for file operations

    @Inject
    CamelContext context;

    @Inject
    ProducerTemplate producerTemplate;

    @Inject
    ConsumerTemplate consumerTemplate;

    @Path("/load/component/mina-sftp")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response loadComponentMinaSftp() throws Exception {
        /* This is an autogenerated test */
        if (context.getComponent(COMPONENT_MINA_SFTP) != null) {
            return Response.ok().build();
        }
        LOG.warnf("Could not load [%s] from the Camel context", COMPONENT_MINA_SFTP);
        return Response.status(500, COMPONENT_MINA_SFTP + " could not be loaded from the Camel context").build();
    }

    @Path("/get/{fileName}")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response getFile(@PathParam("fileName") String fileName) {
        String result = consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp?password=admin&localWorkDirectory=target&fileName="
                        + fileName,
                TIMEOUT_MS,
                String.class);
        return result != null ? Response.ok(result).build() : Response.status(204).build();
    }

    @Path("/create/{fileName}")
    @POST
    @Consumes(MediaType.TEXT_PLAIN)
    public Response createFile(@PathParam("fileName") String fileName, String fileContent)
            throws Exception {
        producerTemplate.sendBodyAndHeader(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp?password=admin", fileContent,
                Exchange.FILE_NAME, fileName);
        return Response
                .created(new URI("https://camel.apache.org/"))
                .build();
    }

    @Path("/delete/{fileName}")
    @DELETE
    public void deleteFile(@PathParam("fileName") String fileName) {
        consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp?password=admin&delete=true&fileName="
                        + fileName,
                TIMEOUT_MS,
                String.class);
    }

    @Path("/moveToDoneFile/{fileName}")
    @PUT
    public void moveToDoneFile(@PathParam("fileName") String fileName) {
        consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp?password=admin&move=${headers.CamelFileName}.done&fileName="
                        + fileName,
                TIMEOUT_MS,
                String.class);
    }

    @Path("/createInSubdir/{subdirectory}/{fileName}")
    @POST
    @Consumes(MediaType.TEXT_PLAIN)
    public Response createFileInSubdirectory(@PathParam("subdirectory") String subdirectory,
            @PathParam("fileName") String fileName, String fileContent) throws Exception {
        producerTemplate.sendBodyAndHeader(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp/" + subdirectory + "?password=admin",
                fileContent,
                Exchange.FILE_NAME, fileName);
        return Response.created(new URI("https://camel.apache.org/")).build();
    }

    @Path("/getFromSubdir/{subdirectory}/{fileName}")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response getFileFromSubdirectory(@PathParam("subdirectory") String subdirectory,
            @PathParam("fileName") String fileName) {
        String result = consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp/" + subdirectory
                        + "?password=admin&localWorkDirectory=target&fileName=" + fileName,
                TIMEOUT_MS,
                String.class);
        return result != null ? Response.ok(result).build() : Response.status(204).build();
    }

    @Path("/list/{directory}")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String listFiles(@PathParam("directory") String directory) {
        String response = consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp/" + directory
                        + "?password=admin&localWorkDirectory=target&noop=true",
                TIMEOUT_MS,
                String.class);
        return response != null ? "file_found" : "no_files";
    }

    @Path("/append/{fileName}")
    @PUT
    @Consumes(MediaType.TEXT_PLAIN)
    public Response appendToFile(@PathParam("fileName") String fileName, String content) {
        producerTemplate.sendBodyAndHeader(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp?password=admin&fileExist=Append",
                content,
                Exchange.FILE_NAME, fileName);
        return Response.ok().build();
    }

    @Path("/exists/{fileName}")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String fileExists(@PathParam("fileName") String fileName) {
        String result = consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp?password=admin&noop=true&fileName="
                        + fileName,
                TIMEOUT_MS,
                String.class);
        return result != null ? "true" : "false";
    }

    @Path("/recursiveList")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String listFilesRecursive() {
        String response = consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp?password=admin&recursive=true&noop=true&localWorkDirectory=target",
                TIMEOUT_MS,
                String.class);
        return response != null ? "files_found" : "no_files";
    }

    @Path("/moveToDirectory/{fileName}/{targetDir}")
    @PUT
    public void moveToDirectory(@PathParam("fileName") String fileName, @PathParam("targetDir") String targetDir) {
        consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp?password=admin&move=../" + targetDir
                        + "/${file:name}&fileName=" + fileName,
                TIMEOUT_MS,
                String.class);
    }

    @Path("/filterByPrefix/{prefix}")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String filterFilesByPrefix(@PathParam("prefix") String prefix) {
        String response = consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp?password=admin&fileName=" + prefix
                        + "*&noop=true&localWorkDirectory=target",
                TIMEOUT_MS,
                String.class);
        return response != null ? "matched" : "no_match";
    }

    @Path("/download/{fileName}")
    @GET
    @Produces(MediaType.APPLICATION_OCTET_STREAM)
    public byte[] downloadFile(@PathParam("fileName") String fileName) {
        return consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp?password=admin&localWorkDirectory=target&fileName="
                        + fileName,
                TIMEOUT_MS,
                byte[].class);
    }

    @Path("/createWithCharset/{fileName}")
    @POST
    @Consumes(MediaType.TEXT_PLAIN)
    public Response createFileWithCharset(@PathParam("fileName") String fileName, String fileContent)
            throws Exception {
        producerTemplate.sendBodyAndHeader(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp?password=admin&charset=UTF-8",
                fileContent,
                Exchange.FILE_NAME, fileName);
        return Response.created(new URI("https://camel.apache.org/")).build();
    }

    @Path("/getWithCharset/{fileName}")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response getFileWithCharset(@PathParam("fileName") String fileName) {
        String result = consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp?password=admin&charset=UTF-8&localWorkDirectory=target&fileName="
                        + fileName,
                TIMEOUT_MS,
                String.class);
        return result != null ? Response.ok(result).build() : Response.status(204).build();
    }

    @Path("/createWithTempFile/{fileName}")
    @POST
    @Consumes(MediaType.TEXT_PLAIN)
    public Response createFileWithTempFile(@PathParam("fileName") String fileName, String fileContent)
            throws Exception {
        producerTemplate.sendBodyAndHeader(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp?password=admin&tempFileName=temp-${file:name}",
                fileContent,
                Exchange.FILE_NAME, fileName);
        return Response.created(new URI("https://camel.apache.org/")).build();
    }

    @Path("/overwrite/{fileName}")
    @PUT
    @Consumes(MediaType.TEXT_PLAIN)
    public Response overwriteFile(@PathParam("fileName") String fileName, String content) {
        producerTemplate.sendBodyAndHeader(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp?password=admin&fileExist=Override",
                content,
                Exchange.FILE_NAME, fileName);
        return Response.ok("overwritten").build();
    }

    @Path("/createWithAutoCreate/{subdirectory}/{fileName}")
    @POST
    @Consumes(MediaType.TEXT_PLAIN)
    public Response createFileWithAutoCreate(@PathParam("subdirectory") String subdirectory,
            @PathParam("fileName") String fileName, String fileContent) throws Exception {
        producerTemplate.sendBodyAndHeader(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp/" + subdirectory
                        + "?password=admin&autoCreate=true",
                fileContent,
                Exchange.FILE_NAME, fileName);
        return Response.created(new URI("https://camel.apache.org/")).build();
    }

    // HIGH PRIORITY #1: Private Key Authentication Tests

    @Path("/createWithPrivateKey/{fileName}")
    @POST
    @Consumes(MediaType.TEXT_PLAIN)
    public Response createFileWithPrivateKey(@PathParam("fileName") String fileName, String fileContent)
            throws Exception {
        producerTemplate.sendBodyAndHeader(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp"
                        + "?privateKeyFile=src/test/resources/ssh/test-key-rsa",
                fileContent,
                Exchange.FILE_NAME, fileName);
        return Response.created(new URI("https://camel.apache.org/")).build();
    }

    @Path("/getWithPrivateKey/{fileName}")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response getFileWithPrivateKey(@PathParam("fileName") String fileName) {
        String result = consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp"
                        + "?privateKeyFile=src/test/resources/ssh/test-key-rsa&localWorkDirectory=target&fileName="
                        + fileName,
                TIMEOUT_MS,
                String.class);
        return result != null ? Response.ok(result).build() : Response.status(204).build();
    }

    @Path("/createWithEncryptedKey/{fileName}")
    @POST
    @Consumes(MediaType.TEXT_PLAIN)
    public Response createFileWithEncryptedKey(@PathParam("fileName") String fileName, String fileContent)
            throws Exception {
        producerTemplate.sendBodyAndHeader(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp"
                        + "?privateKeyFile=src/test/resources/ssh/test-key-rsa-encrypted&privateKeyPassphrase=testpass",
                fileContent,
                Exchange.FILE_NAME, fileName);
        return Response.created(new URI("https://camel.apache.org/")).build();
    }

    @Path("/getWithEncryptedKey/{fileName}")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response getFileWithEncryptedKey(@PathParam("fileName") String fileName) {
        String result = consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp"
                        + "?privateKeyFile=src/test/resources/ssh/test-key-rsa-encrypted&privateKeyPassphrase=testpass&localWorkDirectory=target&fileName="
                        + fileName,
                TIMEOUT_MS,
                String.class);
        return result != null ? Response.ok(result).build() : Response.status(204).build();
    }

    // HIGH PRIORITY #2: Streaming Download Tests

    @Path("/streamDownload/{fileName}")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response streamDownloadFile(@PathParam("fileName") String fileName) {
        java.io.InputStream is = consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp"
                        + "?password=admin&streamDownload=true&localWorkDirectory=target&fileName=" + fileName,
                TIMEOUT_MS,
                java.io.InputStream.class);
        if (is == null) {
            return Response.status(204).build();
        }
        try {
            String content = new String(is.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8);
            return Response.ok(content).build();
        } catch (Exception e) {
            throw new RuntimeException("Failed to read stream", e);
        }
    }

    @Path("/streamDownloadPartial/{fileName}")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response streamDownloadPartialRead(@PathParam("fileName") String fileName) {
        java.io.InputStream is = consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp"
                        + "?password=admin&streamDownload=true&localWorkDirectory=target&fileName=" + fileName,
                TIMEOUT_MS,
                java.io.InputStream.class);
        if (is == null) {
            return Response.status(204).build();
        }
        try {
            // Read only first 10 bytes
            byte[] buffer = new byte[10];
            int bytesRead = is.readNBytes(buffer, 0, 10);
            String content = new String(buffer, 0, bytesRead, java.nio.charset.StandardCharsets.UTF_8);
            return Response.ok(content).build();
        } catch (Exception e) {
            throw new RuntimeException("Failed to read stream", e);
        }
    }

    // HIGH PRIORITY #4: Error Handling Scenarios

    @Path("/error/wrongPassword/{fileName}")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response testWrongPassword(@PathParam("fileName") String fileName) {
        try {
            consumerTemplate.receiveBody(
                    "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp"
                            + "?password=wrongpassword&localWorkDirectory=target&fileName=" + fileName,
                    TIMEOUT_MS,
                    String.class);
            return Response.ok("SHOULD_NOT_SUCCEED").build();
        } catch (Exception e) {
            return Response.status(401).entity("AUTH_FAILED").build();
        }
    }

    @Path("/error/nonExistentFile/{fileName}")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response testNonExistentFile(@PathParam("fileName") String fileName) {
        String result = consumerTemplate.receiveBody(
                "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp"
                        + "?password=admin&localWorkDirectory=target&fileName=" + fileName,
                TIMEOUT_MS,
                String.class);
        return result == null ? Response.status(404).entity("NOT_FOUND").build()
                : Response.ok(result).build();
    }

    @Path("/error/invalidPath/{fileName}")
    @POST
    @Consumes(MediaType.TEXT_PLAIN)
    public Response testInvalidPath(@PathParam("fileName") String fileName, String fileContent) {
        try {
            producerTemplate.sendBodyAndHeader(
                    "mina-sftp://admin@localhost:{{camel.sftp.test-port}}/sftp/nonexistent/deep/path"
                            + "?password=admin&autoCreate=false",
                    fileContent,
                    Exchange.FILE_NAME, fileName);
            return Response.ok("SHOULD_NOT_SUCCEED").build();
        } catch (Exception e) {
            return Response.status(500).entity("PATH_ERROR").build();
        }
    }
}
